### ISSUE TITLE
React.PureComponent with out props injection? Looking for guidance.

### ISSUE THREAD

**Issue by celgra** [codergvbrownsville/code-rgv-pwa#7]
@piq9117 
https://github.com/codergvbrownsville/code-rgv-pwa/blob/master/src/pages/Home/Home.tsx

I was under the impression that PureComponents are simply internally setup with a shallow comparison implementation of shouldComponentUpdate(). Without a constructor passing in props or initializing state, how is it different from a functional component? 

Yours  truly,
A Concerned Citizen

**Comment by piq9117** [comment]
According to the [docs](https://facebook.github.io/react/docs/react-api.html#react.purecomponent) its exactly like `React.Component`, but it implements `shouldComponentUpdate` to check for comparison. I used to implement this with [react-pure-renderer-utils](https://github.com/liady/react-pure-render-utils). However, since react implements it internally now I'll just use that.

I was trying it out on the Home component.lol. Sorry to confuse you.
